/*
 * MERKI medication parser — pattern compiler.
 *
 * Copyright 2007 Sigfried Gold.  Part of MERKI, GPL-3.0-or-later.
 *
 * Port of applyConvenienceRules / makeTerminalPatterns / makeNonTerminalPatterns
 * from ParseMeds.pm.  Expands the named-regex grammar in rules.ts into real,
 * fully-expanded regex source strings (one per terminal and nonTerminal).
 *
 * The Perl prints compiled regexes as `(?^:...)`; the only Perl-only construct
 * that appears in these patterns is that `(?^:` wrapper (a flag-reset
 * non-capturing group).  In JS it is just a non-capturing group, so we emit
 * `(?:` directly.  Everything else (lookbehind, lookahead, \b \d \w \s,
 * alternation, quantifiers) maps 1:1 to modern JS regex.
 */

import { rules, SPLIT_DELIM, type Rules } from './rules.js';

/** Compiled regex source strings keyed by terminal / nonTerminal name. */
export type PatternMap = Record<string, string>;

/**
 * applyConvenienceRules: expand terminal alternatives (e.g. "mg" -> "mg.",
 * "mgs", "mgs.").  Returns a fresh terminals map; does not mutate the input.
 *
 * Perl iterates convenience-rule keys in (randomized) hash order, so the exact
 * order of appended expansions is not stable run-to-run.  We iterate in the
 * declared object-key order for determinism; the surrounding split-delimiter
 * boundaries make alternation order irrelevant to what actually matches.
 */
function applyConvenienceRules(r: Rules): Record<string, string[]> {
  const { terminals, convenienceRules } = r;
  const expansions: Record<string, string[]> = {};

  const expand = (ruleName: string, original: string): string => {
    switch (ruleName) {
      case 'dotsAfterLtrOk': // each letter may be followed by a dot: bid -> b.i.d.
        return original.replace(/(.)/g, '$1\\.');
      case 'dotsAtEndOk': // trailing dot ok: mg -> mg.
        return original + '\\.';
      case 'canBePlural': // trailing s ok: tab -> tabs
        return original + 's';
      case 'plurDotAtEnd': // trailing s.: mg -> mgs.
        return original + 's\\.';
      default:
        throw new Error(`don't know how to handle convenience rule ${ruleName}`);
    }
  };

  for (const ruleName of Object.keys(convenienceRules)) {
    for (const original of convenienceRules[ruleName]!) {
      (expansions[original] ??= []).push(expand(ruleName, original));
    }
  }

  const out: Record<string, string[]> = {};
  for (const [name, alts] of Object.entries(terminals)) {
    const extra: string[] = [];
    for (const expr of alts) {
      if (expansions[expr]) extra.push(...expansions[expr]!);
    }
    out[name] = [...alts, ...extra];
  }
  return out;
}

/** makeTerminalPatterns: wrap each terminal's alternation in split delimiters. */
function makeTerminalPatterns(terminals: Record<string, string[]>): PatternMap {
  const patterns: PatternMap = {};
  for (const [name, alts] of Object.entries(terminals)) {
    patterns[name] = `${SPLIT_DELIM}(${alts.join('|')})${SPLIT_DELIM}`;
  }
  return patterns;
}

/**
 * makeNonTerminalPatterns: expand nonTerminal patterns by substituting every
 * bare alpha word with the (already-compiled) pattern it names.  Mutates
 * `patterns` in place, adding one entry per nonTerminal.  NonTerminals must be
 * processed in declaration order so earlier ones are available to later ones.
 *
 * This is a deliberately literal port of the Perl sub (ParseMeds.pm), warts and
 * all, because the reference fixtures were generated by exactly this behavior.
 * Two of those warts matter:
 *
 *  - Only the FIRST escape gets the \b -> splitDelim swap (see below).  This
 *    looks like a bug, and arguably is, but it produces BETTER parses than the
 *    "obvious fix" of swapping every \b: splitDelim
 *    `(\b|(?=\d)|(?<=\d)|(?=\W)|$)` is far looser than a bare \b, so swapping
 *    every \b lets junk like "started on 03/15/2024" match `possibleDrug`'s
 *    `possibleDrugName \b dose \b instructions` alternative (the second \b
 *    stops requiring a real word boundary between the date pieces).  Leaving
 *    later \b's literal keeps `possibleDrug` appropriately strict.  DO NOT
 *    "fix" this without regenerating every fixture.
 *
 *  - The escape stash only grabs ONE char after \ ! or = (Perl: the comment
 *    says "chars" plural but the regex is singular).  Fine here because \b is
 *    the only escape that appears in the grammar and it's a single letter.
 */
function makeNonTerminalPatterns(patterns: PatternMap, r: Rules): void {
  for (const nt of r.nonTerminals) {
    const expanded: string[] = [];
    for (let pattern of nt.patterns) {
      // Any alpha chars are names of other patterns, EXCEPT a char following
      // \ ! or = which is a regex bit (the comment in the Perl says \s, \d but
      // in this grammar only \b ever appears).  Stash those so they aren't
      // treated as pattern names.
      const escs: string[] = [];
      pattern = pattern.replace(/(\\|!|=)[a-zA-Z]/g, (m) => {
        escs.push(m);
        return '====';
      });

      // Validate that every remaining alpha run names a known pattern.  In the
      // Perl this is gated on {DEBUG}, but DEBUG is hard-set to 1, so it always
      // runs; we keep it always-on — it's cheap and catches grammar typos.
      for (const m of pattern.matchAll(/[a-zA-Z]+/g)) {
        if (patterns[m[0]] === undefined) {
          throw new Error(`could not find pattern for term [${m[0]}]`);
        }
      }

      // Replace each name with its compiled pattern, wrapped to swallow
      // surrounding whitespace.
      pattern = pattern.replace(
        /[a-zA-Z]+/g,
        (name) => `((?=\\s*)(?:${patterns[name]})(?=\\s*))`,
      );

      // Restore the stashed escapes in order.  Perl fixes up ONLY escs[0]
      // (\b -> splitDelim) once, before the consume loop, so only the first
      // escape is ever swapped; every later \b is restored literally.  We
      // replicate that exactly — see the wart note above.
      if (escs.length) {
        if (escs[0] === '\\b') escs[0] = SPLIT_DELIM;
        let i = 0;
        pattern = pattern.replace(/====/g, () => escs[i++]!);
      }

      expanded.push(pattern);
    }
    patterns[nt.name] = `(${expanded.join('|')})`;
  }
}

/**
 * Build the full pattern map (terminals + nonTerminals), then compile each into
 * a global RegExp.  The boundary-wrapped terminal patterns are inserted inside
 * larger nonTerminal regexes as raw source, so we keep both the source strings
 * (for composition) and compiled RegExps (for matching) available.
 */
export function buildPatterns(r: Rules = rules): {
  source: PatternMap;
  compiled: Record<string, RegExp>;
} {
  const terminals = applyConvenienceRules(r);
  const source = makeTerminalPatterns(terminals);
  makeNonTerminalPatterns(source, r);

  const compiled: Record<string, RegExp> = {};
  for (const [name, src] of Object.entries(source)) {
    compiled[name] = new RegExp(src, 'g');
  }
  return { source, compiled };
}
